"""Stage 3 — VoiceClone via CosyVoice or IndexTTS.

For each segment in `voice_clone.json`, looks up the speaker's reference wav
(via `prompt_voices/manifest.json`), and synthesizes a per-segment wav.

Supports two TTS backends:
    - cosyvoice: Fun-CosyVoice3 (zero_shot/instruct/cross_lingual modes)
    - indextts:  IndexTTS-2 (voice cloning with emotion control)

Usage:
    python step3_clone.py --input path/to/story.txt
    python step3_clone.py --input path/to/story.txt --tts-model cosyvoice
    python step3_clone.py --input path/to/story.txt --tts-model indextts
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import config, tts_client


def main() -> int:
    args = _parse_args()
    tts_model = args.tts_model or config.CLONE_MODEL
    if tts_model not in ("cosyvoice", "indextts"):
        print(f"[error] invalid --tts-model {tts_model!r}", file=sys.stderr)
        return 1

    out_dir = config.story_output_dir(args.input)
    clone_path = out_dir / "voice_clone.json"
    manifest_path = out_dir / "prompt_voices" / "manifest.json"
    for p in (clone_path, manifest_path):
        if not p.is_file():
            print(f"[error] {p} not found — run earlier steps first",
                  file=sys.stderr)
            return 1

    clone = json.loads(clone_path.read_text(encoding="utf-8"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    segments_dir = out_dir / "segments"
    segments_dir.mkdir(parents=True, exist_ok=True)

    for seg in clone["segments"]:
        sid = seg["segment_id"]
        out_wav = segments_dir / f"{sid:04d}.wav"
        if out_wav.exists() and not args.force:
            print(f"[skip] {out_wav.name} already exists")
            continue

        speaker = seg["speaker"]
        if speaker not in manifest:
            print(f"[error] segment {sid}: speaker {speaker!r} missing from "
                  f"manifest — regenerate via step2_design.py", file=sys.stderr)
            return 1

        ref_wav_path = out_dir / manifest[speaker]["wav_path"]
        sample_text = manifest[speaker]["sample_text"]
        prompt_audio_b64 = tts_client.wav_to_b64(ref_wav_path)

        print(f"[step3] cloning segment {sid:04d} ({speaker}, {tts_model}) ...")

        if tts_model == "cosyvoice":
            wav_bytes = _clone_cosyvoice(seg, sample_text, prompt_audio_b64)
        else:  # indextts
            wav_bytes = _clone_indextts(seg, prompt_audio_b64)

        out_wav.write_bytes(wav_bytes)

    print(f"[step3] done ({tts_model}), wavs in {segments_dir}")
    return 0


def _clone_cosyvoice(seg: dict, sample_text: str, prompt_audio_b64: str) -> bytes:
    """Synthesize using Fun-CosyVoice3."""
    mode = seg.get("mode", config.CLONE_MODE)
    if mode not in ("zero_shot", "instruct", "cross_lingual"):
        mode = "zero_shot"

    if mode == "zero_shot":
        prompt_text = (
            "You are a helpful assistant. "
            f"{seg['instruct']}"
            "<|endofprompt|>"
            f"{sample_text}"
        )
    else:  # instruct / cross_lingual — instruction only
        prompt_text = (
            "You are a helpful assistant. "
            f"{seg['instruct']}"
            "<|endofprompt|>"
        )

    return tts_client.cosyvoice_generate(
        text=seg["text"],
        prompt_text=prompt_text,
        prompt_audio_b64=prompt_audio_b64,
        mode=mode,
    )


def _clone_indextts(seg: dict, prompt_audio_b64: str) -> bytes:
    """Synthesize using IndexTTS-2 with emotion control from tts_params."""
    # Get tts_params from segment (generated by step1 with indextts prompt)
    tts_params = seg.get("tts_params", {})

    return tts_client.indextts_generate(
        text=seg["text"],
        reference_audio_b64=prompt_audio_b64,
        emotion_vector=tts_params.get("emotion_vector"),
        emotion_alpha=tts_params.get("emotion_alpha", 1.0),
        temperature=tts_params.get("temperature"),
        top_p=tts_params.get("top_p"),
        top_k=tts_params.get("top_k"),
        num_beams=tts_params.get("num_beams"),
        repetition_penalty=tts_params.get("repetition_penalty"),
        max_text_tokens=tts_params.get("max_text_tokens"),
        max_mel_tokens=tts_params.get("max_mel_tokens"),
        interval_silence=tts_params.get("interval_silence"),
    )


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Stage 3: per-segment VoiceClone",
        epilog="""
Examples:
    python step3_clone.py --input story.txt
    python step3_clone.py --input story.txt --tts-model indextts
        """,
    )
    p.add_argument("--input", required=True,
                   help="path to source .txt (used to locate outputs/<stem>/)")
    p.add_argument("--tts-model", choices=["cosyvoice", "indextts"],
                   help=f"TTS model for cloning (defaults to config.CLONE_MODEL={config.CLONE_MODEL})")
    p.add_argument("--mode", choices=["zero_shot", "instruct", "cross_lingual"],
                   help="CosyVoice generation mode (only for cosyvoice model)")
    p.add_argument("--force", action="store_true",
                   help="Overwrite existing output files")
    return p.parse_args()


if __name__ == "__main__":
    sys.exit(main())